stages:
  - build
  - deploy

variables:
  BUILD_DIR: build

cache:
  key: "enabel-web-node-module"
  paths:
    - node_modules/

before_script:
  - export NVM_DIR=$HOME/.nvm;
  - source $NVM_DIR/nvm.sh;

build_dev:
  stage: build
  tags:
    - web
  environment: development
  only:
    - backend
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - $BUILD_DIR/

build_prod:
  stage: build
  tags:
    - web
  environment: production
  only:
    - main
  script:
    - node --version
    - npm install
    - npm run build
  artifacts:
    paths:
      - $BUILD_DIR/

# 🔹 Build pour Tshopo (env spécifique)
build_tshopo:
  stage: build
  tags:
    - web
  environment: production
  only:
    - tshopo-admin
  script:
    - npm install
    - npm run build:tshopo
  artifacts:
    paths:
      - $BUILD_DIR/

deploy_dev:
  stage: deploy
  tags:
    - web
  environment: development
  only:
    - backend
  script:
    - scp -r $BUILD_DIR/* root@172.16.18.210:/var/www/enabel_admin

deploy_prod:
  stage: deploy
  tags:
    - web
  environment: production
  only:
    - main
  script:
    - scp -r $BUILD_DIR/* root@172.16.18.26:/var/www/devbuy

# 🔹 Déploiement spécifique à la branche tshopo-admin
deploy_tshopo_admin:
  stage: deploy
  tags:
    - web
  environment: production
  only:
    - tshopo-admin
  before_script:
    - mkdir -p ~/.ssh
    - cp .ci-ssh/deploy.key ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  script:
    - scp -r $BUILD_DIR/* root@180.149.199.23:/var/www/tshopo.admin/html/
  after_script:
    - rm -f ~/.ssh/id_rsa
