stages:
  - build
  - deploy

# Variables globales
variables:
  BUILD_DIR: build
  NODE_OPTIONS: "--max-old-space-size=4096" # Limite mémoire pour éviter le crash de build

# Cache pour accélérer les builds
cache:
  key: "tshopo-admin-node-module"
  paths:
    - node_modules/

before_script:
  - export NVM_DIR=$HOME/.nvm
  - source $NVM_DIR/nvm.sh

# Build pour tshopo-admin en dev
build_dev:
  stage: build
  tags:
    - web
  environment: development
  only:
    - tshopo-admin
  script:
    - npm install
    - npm run build:tshopo
  artifacts:
    paths:
      - $BUILD_DIR/

# Build de production (branche main)
build_prod:
  stage: build
  tags:
    - web
  environment: production
  only:
    - main
  script:
    - node --version
    - npm install
    - npm run build:tshopo
  artifacts:
    paths:
      - $BUILD_DIR/

#Déploiement vers le serveur de développement
deploy_dev:
  stage: deploy
  tags:
    - web
  environment: development
  only:
    - tshopo-admin
  before_script:
    - mkdir -p ~/.ssh
    - cp .ci-ssh/deploy.key ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  script:
    - scp -r $BUILD_DIR/* root@180.149.199.23:/var/www/tshopo.admin/html/
  after_script:
    - rm -f ~/.ssh/id_rsa

# Déploiement vers le serveur de production
deploy_prod:
  stage: deploy
  tags:
    - web
  environment: production
  only:
    - main
  before_script:
    - mkdir -p ~/.ssh
    - cp .ci-ssh/deploy.key ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  script:
    - scp -r $BUILD_DIR/* root@172.16.18.26:/var/www/devbuy
  after_script:
    - rm -f ~/.ssh/id_rsa
